### ISSUE TITLE
The ego vehicle sometimes fails to stop at yellow lights

### ISSUE THREAD

**Issue by shmpwk** [tier4/AWSIM#10]
[Description]
The ego vehicle should stop at yellow lights by Autoware default, but sometimes fails.

[Cause of the problem]
The recognized color can be checked in `/perception/traffic_light_recognition/traffic_signals` corresponding to the `map_primitive_id` of the traffic light.
The yellow signal is `color: 2`, but it is sometimes recognized as `color: 16` (unknown). 
When the ego vehicle is at a high speed or getting too close to the intersection, it it seemed to be recognized as `color: 16`.

[Possible approach]
The yellow color needs to be fine-tuned on the AWSIM side.
The current yellow color is set [here](https://github.com/tier4/AWSIM/blob/main/Assets/AWSIM/Prefabs/Environments/Nishishinjuku/Nishishinjuku%20RandomTraffic.prefab) or [here](https://github.com/tier4/AWSIM/blob/main/Assets/AWSIM/Prefabs/Environments/Nishishinjuku/Nishishinjuku.prefab), showing that the yellow color is represented as `r: 1, g: 0.92156863, b: 0.015686275, a: 1`.
I reproduced the color with [an web app](https://tomari.org/main/java/color/gen.html), and it was indeed yellow. 
However, it may be different from the expected yellow color, thus it should be adjusted.

[Video link](https://user-images.githubusercontent.com/42209144/196145013-01608003-2330-4f3a-9388-fa9033704a22.webm)

**Comment by mackierx111** [comment]
solved https://github.com/tier4/AWSIM/pull/60
