### ISSUE TITLE
AWSIM and autoware 2d goal no route

### ISSUE THREAD

**Issue by yangjiameng** [tier4/AWSIM#100]
### Checklist

- [X] I've read the [contribution guidelines](https://tier4.github.io/AWSIM/DeveloperGuide/HowToContribute/).
- [X] I've searched other issues and no duplicate issues were found.

### Description

I use AWSIM v 1.0.1 and autoware galactic , and I use 2d goal button to set goal position, however, no route , no planning

### Purpose

no

### Possible approaches

no

### Definition of done

no

**Comment by robodrome** [comment]
Try this:
https://github.com/tier4/AWSIM/issues/91
