### ISSUE TITLE
lanelet2 map is unable to load into unity

### ISSUE THREAD

**Issue by zhuyingxiang95** [tier4/AWSIM#136]
### Checklist

- [X] I've read the [contribution guidelines](https://tier4.github.io/AWSIM/DeveloperGuide/HowToContribute/).
- [X] I've searched other [issues](https://github.com/tier4/AWSIM/issues?q=is%3Aissue) and [discussions Q&A category](https://github.com/orgs/autowarefoundation/discussions/categories/q-a). I found no duplicate issues.
- [X] I'm convinced that this is not my fault but a bug.

### Description

hello guys, I have a lanelet2 map which is converted from another map format. I have tried to import and run  it in Autoware. it works fine. when i tried to load it into unity. it failed and the error is  : an item with the same key is already added.  I guess its something wrong between lanelet2 container script and the lanelet2 file itself. I will appreciate if somesone could  give me some help.

### Expected behavior

lanelet2 map successfully loaded

### Actual behavior

cant load lanelet2 map into unity editor

### Steps to reproduce

load lanelet2 map in a customized scene

**Comment by zhuyingxiang95** [comment]
![Screenshot from 2023-05-30 10-55-11](https://github.com/tier4/AWSIM/assets/74554419/d43e2797-df75-4335-93ce-50b0bac9d1ed)
here is the error screenshot.

**Comment by zhuyingxiang95** [comment]
@shmpwk could you please have a look into this issue ?

**Comment by zhuyingxiang95** [comment]
this issue is fixed by switching all the node ID ,Lanelets ID into positive. and i guess the code of lanelets_map.cs has a bug in dealing with the negative ID of nodes ,ID of lanelets.  
![Screenshot from 2023-05-30 18-27-34](https://github.com/tier4/AWSIM/assets/74554419/34c22756-6153-454c-92b3-17e446a3c009)
I think here we need a setter function to set the value of count , if we don't do that, this.count==0 will be always true. and the unique ID will always be 1. This is the reason for the error why it showed the same key has added yet.

**Comment by zhuyingxiang95** [comment]
now another issue is the lanelet2 map could not be fully loaded and it shows the following error. The same lanelet 2 map works fine in autoware ![Screenshot from 2023-05-30 18-35-15](https://github.com/tier4/AWSIM/assets/74554419/d399054c-30fa-4eac-bfe9-61687cf9ee85)
here i attached the lanelet2 map i used
[lanelet2_map.zip](https://github.com/tier4/AWSIM/files/11602341/lanelet2_map.zip)

**Comment by zhuyingxiang95** [comment]
@mackierx111 could you please have a look into this issue ?

**Comment by mackierx111** [comment]
@zhuyingxiang95 
Thanks for the report. Improved lanelet loading. https://github.com/tier4/AWSIM/pull/172
