### ISSUE TITLE
Lidar not hitting Unity Terrain

### ISSUE THREAD

**Issue by Ushtarador** [tier4/AWSIM#145]
### Checklist

- [X] I've read the [contribution guidelines](https://tier4.github.io/AWSIM/DeveloperGuide/HowToContribute/).
- [X] I've searched other issues and no duplicate issues were found.

### Description

Hey all,
I've created some custom offroad terrain using the Unity Terrain editor, but unfortunately the lidar does not register hits on the terrain. My terrain has a Terrain Collider, but I guess that doesn't seem to work - can anyone suggest a smart workaround for this problem?

**Comment by Ushtarador** [comment]
Just a small update, I currently worked around the issue by exporting my terrain as a mesh to a .obj file, and then reimporting it, overlaying it with the terrain and assigning it an invisible material. It works for now but I really don't like it ^^

**Comment by mackierx111** [comment]
Currently, [RGL](https://github.com/RobotecAI/ros2-for-unity) cannot take terrain into account. It has not yet been determined whether RGL will support it in the future.

**Comment by msz-rai** [comment]
Good news! We are currently working to support terrain by LiDARs (by `RGLUnityPlugin`). I am sharing some early results. The feature will be merged into the main branch soon.

<img src="https://github.com/tier4/AWSIM/assets/112629916/34c88a7e-c68d-49e6-9791-3d3791479cab" width="400">
<img src="https://github.com/tier4/AWSIM/assets/112629916/64076a0c-23b2-470c-8592-17a8b56916a1" width="400">

**Comment by jediofgever** [comment]
> Just a small update, I currently worked around the issue by exporting my terrain as a mesh to a .obj file, and then reimporting it, overlaying it with the terrain and assigning it an invisible material. It works for now but I really don't like it ^^

That is hardly a remedy, I did the same temporarily, but what about other objects, e.g trees or plants ? Great news that they are working toward it.

**Comment by Jakub-Krakowiak** [comment]
Good news, terrain is now supported as [our pr](https://github.com/tier4/AWSIM/pull/173) has been merged.
