### ISSUE TITLE
I am able to localize, but the 2D goal pose is not being set.

### ISSUE THREAD

**Issue by Aysenayilmaz** [tier4/AWSIM#162]
### Checklist

- [X] I've read the [contribution guidelines](https://tier4.github.io/AWSIM/DeveloperGuide/HowToContribute/).
- [X] I've searched other [issues](https://github.com/tier4/AWSIM/issues?q=is%3Aissue) and [discussions Q&A category](https://github.com/orgs/autowarefoundation/discussions/categories/q-a). I found no duplicate issues.
- [X] I'm convinced that this is not my fault but a bug.

### Description

While creating a new environment, I set the point cloud map of the desired area in Unity to (0, 0, 0) and built the environment accordingly. When extracting the point cloud map from the simulation, I added the generated Lanelet2 map (for pointcloudmapper) to AWSIM based on the point cloud map I used. In Unity, they are positioned in unrelated locations and I manually aligned them by adjusting, but they still don't align perfectly on the Z-axis. Manually adjusting and the incomplete alignment on the Z-axis feel unreliable to me.  _**(The elevation difference is also visible in the photo below.)**_

![Screenshot from 2023-07-10 14-42-31](https://github.com/tier4/AWSIM/assets/108546951/4dd836c4-d295-4c7d-966d-db14059c7aff)

When I run the simulation according to the documentation with Autoware, the vehicle appears in a completely unrelated location. And I am unable to set the 2D goal pose.

![rre](https://github.com/tier4/AWSIM/assets/108546951/926bc274-3d2d-46ae-8857-5ea7fa5669b1)

I have recorded a video regarding this issue, and I am attaching it. I am also attaching a photo in case the text flowing in the terminal is not clear.

https://github.com/tier4/AWSIM/assets/108546951/a47ac4ff-b7c0-44f4-afb8-fb31adf87999

- _**If there is a possibility that the video may not be visible, I have uploaded the same video to YouTube as unlisted. Here is the link:  https://youtu.be/wAG3QNx21XQ **_ 

![t_e](https://github.com/tier4/AWSIM/assets/108546951/2186c43d-c0e5-422d-ae04-b00297bbbccd)

I tried this again with the demo version (AWSIM_v1.1.0) mentioned in the AWSIM documentation, and this time it localized correctly but the 2D goal pose still couldn't be set. And the error in the terminal is as shown in the image I attached above. When I run the 'AWSIM_v1.1.0' simulation in the planning simulator instead of the e2e simulator, I am able to provide a 2D goal pose and drive the vehicle autonomously. However, I am unable to drive the vehicle autonomously in my own created simulation.

When I run the 'git status' command in the directory where Autoware is located, I get the following result:
 
![f](https://github.com/tier4/AWSIM/assets/108546951/d9cfecd1-c75d-4228-af0c-0f10b54e3972)

_I am also attaching the requirements mentioned in the issues of others who have faced a similar problem._

- launch.log file 

[log.txt](https://github.com/tier4/AWSIM/files/12001789/log.txt)

-`dpkg -l |grep cuda` 

[grep_cuda.txt](https://github.com/tier4/AWSIM/files/12001918/grep_cuda.txt)

`dpkg -l |grep nvidia`

[grep_nvidia.txt](https://github.com/tier4/AWSIM/files/12001927/grep_nvidia.txt)

`nvidia-smi`

![nvidia_smi](https://github.com/tier4/AWSIM/assets/108546951/395b8b89-9745-4dc3-a349-c251949c772c)

`nvcc --version`

![nvcc --version](https://github.com/tier4/AWSIM/assets/108546951/c0c53d77-b94b-45b2-ab52-96f9e54283b0)

### Expected behavior

Ensuring the vehicle starts in the correct position and setting the 2D goal pose.

### Actual behavior

The vehicle is starting in the wrong position, and I am unable to set the 2D goal pose.

### Steps to reproduce

1. Create a new simulation environment.
2. Build the simulation. 
3. Run the sim with autoware and set the 2d goal pose. 

### Versions

- Ubuntu 22.04.2 LTS

- ROS2, Humble

- Unity editor, 2021.1.7f1

### Possible causes

The alignment of Lanelet2 and the environment being done manually may have caused it.

**Comment by Aysenayilmaz** [comment]
I wanted to add a little more detail because I thought there was missing information.

-The osm I use is not made in the vector map builder, but it can be uploaded and installed there.
An exported map.

-These values come by default when I import lanelet. 


![Untitaaaaled](https://github.com/tier4/AWSIM/assets/108546951/471f3a65-2cbe-462e-88a6-f0146ab86d7a)


-This is the coordinate of the environment that I changed.  ( It was previously at (0,0,0) )


![Untitlebbbbbd](https://github.com/tier4/AWSIM/assets/108546951/6460ff23-dd66-49e4-986f-f2342eb3ef69)

**Comment by WJaworskiRobotec** [comment]
@Aysenayilmaz Could you share a 3D environment you have created? I believe it's required to set a MGRS offset properly to align 3D model/PCD with LL2.

**Comment by Aysenayilmaz** [comment]
- I couldn't fully understand the meaning of MGRS offset position, but I realized it's used as a reference point, similar to the map origin. When I used the map origin values used for HD map creation, I noticed they were in UTM format, not MGRS. Directly using these values didn't work as expected. 


![map_origin](https://github.com/tier4/AWSIM/assets/108546951/6becab81-7679-4b20-ab6c-350cc68ecddf)

-  So, I converted the UTM coordinates to MGRS using the website ' https://coordinates-converter.com/en/decimal/41.019635,28.886861?karte=OpenStreetMap&zoom=19 '. I also used  altitude offset value for the Z-axis(In the picture above). 

![transform](https://github.com/tier4/AWSIM/assets/108546951/76bded59-9923-4b86-8814-60cd6e18e8b1)

- When I upload the .ply file (real-life point cloud map of where I want to make the environment) to Cloud Compare, it seems like the values I receive are slightly more accurate, but I'm not entirely sure.

![cc](https://github.com/tier4/AWSIM/assets/108546951/e47337ff-19af-48fb-a408-4fbfb1a9dc4b)

- And right now the hd-map and the environment are not so unrelated to each other. Maybe it's because of terrain object, i'll investigate that.

![result](https://github.com/tier4/AWSIM/assets/108546951/82785a51-08ab-445d-ac85-d4cbf77e0f0d)

_The results I got were all things I realized through a bit of trial and error. So I'm not entirely sure but that's all I could figure out by comparing it to the nishishinjuku map. I look forward to learning exactly what the right process is._

**Comment by WJaworskiRobotec** [comment]
For proper alignment of simulation 3D environment with LL2, to make Autoware's localization work correctly the following MGRS offset parameters has to be set:

> X : 59620
> Y : 42811 

Then, the vehicle is localized using GNSS and Lidar data in the proper place : 

![Screenshot from 2023-07-19 13-33-29](https://github.com/tier4/AWSIM/assets/85557834/572d14b1-6fc7-46fd-8c69-41f03ab6dde7)

I'm now working to make it drive - Autoware logs that the vehicle is outside of the Lanelet, a small shift still has to be corrected.

**Comment by Aysenayilmaz** [comment]
-  In my opinion, if I use ll2 for driving then I must use the ll2's origin values and it’s should be enough for the alignment. After given mgrs offset position, taking all the roads (the created) to (0,0,0) position, ll2 aligned with the roads I created. 


![Untitled](https://github.com/tier4/AWSIM/assets/108546951/7284c687-dcee-4c1a-a21e-ae434a637cfa)



- Terrain's holder is actually in the same spot as all of them, but there is a problem with rotation or something. And as it can be seen in the picture below, the holder of the terrainin stands away from the terrain. That is why terrain cant match the roads and ll2.

![Untitled](https://github.com/tier4/AWSIM/assets/108546951/0a4e16c3-63ce-41a9-8e82-59dfa65b551a)

- It seems that the problem happens during the terrain export( https://github.com/tier4/AWSIM/issues/145 ), and the reason for this is the position values entered for the terrain. I obtain these values from hd-map's mesh, and they are constant and reliable because the HD map was created using the mesh containing these values. When I export the terrain with the position values set to (0, 0, 0), there is no issue with the holder like before. Later, when I enter the terrain's values, the roads, ll2, and terrain align perfectly on top of each other. 


![Untitled](https://github.com/tier4/AWSIM/assets/108546951/3ecda6e8-2ddb-4dae-9861-b7ba3e897d36)

**Comment by Aysenayilmaz** [comment]
Another thing I noticed regarding the MGRS offset position is that when extracting a point cloud map from the simulation using "pointcloudmapper," it is necessary to enter the same values for the MGRS offset position and ROS world origin. 


![Screenshot from 2023-07-24 09-45-32](https://github.com/tier4/AWSIM/assets/108546951/f8bdb78d-15fd-4fb7-a5e6-3c2b4b9d2983)


![Screenshot from 2023-07-24 09-45-39](https://github.com/tier4/AWSIM/assets/108546951/69c204a3-99fb-4b3b-8bcc-e52c020ae4cd)
