### ISSUE TITLE
AWSIM outputs Localization

### ISSUE THREAD

**Issue by taikitanaka3** [tier4/AWSIM#177]
### Checklist

- [X] I've read the [contribution guidelines](https://tier4.github.io/AWSIM/DeveloperGuide/HowToContribute/).
- [X] I've searched other issues and no duplicate issues were found.

### Description

Suggestion
Since AWSIM outputs many sensor data I think it would be better to 
1. add Autoware topic data as `/localization/kinematic_state` with prefab not in default AWSIM.
2. add ground truth data as `/awsim/ground_truth/localization/kinematic_state` with prefab in default AWSIM

https://github.com/tier4/AWSIM/tree/feature/add_odometry_sensor

@mackierx111 
Question 
I think both of above is ok as an open source , which do you think is better?

**Comment by mackierx111** [comment]
merged
https://github.com/tier4/AWSIM/pull/178
