### ISSUE TITLE
AutowareSimulation Scene Keeps Crashing

### ISSUE THREAD

**Issue by rzninvo** [tier4/AWSIM#199]
I have downloaded the most recent [AWSIM source code](https://github.com/tier4/AWSIM/commit/2725ece2dcfbe0bff229ef654f954704fa776f53) (and my Unity version is 2021.1.7f1. When I run AutowareSimulation.unity I get this error and my unity crashes: 
(I have already imported the nishishinjuku unity package)

![image](https://github.com/tier4/AWSIM/assets/46872428/1cb4f6f5-0ef2-4041-9f5b-d585ad3f1138)

**Ubuntu Version: 22.04 LTS**
**Nvidia Graphics:**
![image](https://github.com/tier4/AWSIM/assets/46872428/7b64c548-3f78-4199-9437-626a3398a58c)

**Comment by rzninvo** [comment]
## Quick-Fix 
Found a workaround by changing the Mesh Source of the Scene Manager to the **Only Colliders** option.
![Workaround](https://github.com/tier4/AWSIM/assets/46872428/e38a8569-b79c-4541-9ac7-c48f1eaa99bf)

**Comment by msz-rai** [comment]
This crash is the result of two things:
1. Some game objects had lost their meshes.
2. A bug in `RGLUnityPlugin` that processes invalid objects (with null meshes) endlessly.

For the second point, I have prepared [a PR](https://github.com/tier4/AWSIM/pull/200) that hopefully will be merged soon.
