### ISSUE TITLE
Issue about setting up a new Pose in AWSIM

### ISSUE THREAD

**Issue by yifanfish233** [tier4/AWSIM#204]
Hi,
I'm runningthe simulation on Ubuntu 20.04 with AWSIM v1.0.1, ROS2 galastic.

I noticed that based on the totural, everything goes fine on my computer, however, once I chose to pick a different position by clicking the "2D Pose Estimate" button, the car position in the AWSIM remain the same.(both the camera image I received from topic and lidar pointcloud). but in rviz, the car moves to correct postion on the map.

I can run without issue by launch the AWSIM and autoware, then setup the goal position, but I can't setup the initial pose correctly. Is there something I didn't setup correctly?

Thanks for the time!

**Comment by whbcumtb** [comment]
The correct operation flow is following: 1) start the AWSIM; 2) launch autoware.Then, localization will be initialized automatically in RVIZ. If the car pose is not correctly, you can improve it by clicking the "2D Pose Estimate" button; 3) Setup a goal by clicking the "2D Goal Pose" button. Then the car will move. Good luck!

**Comment by mackierx111** [comment]
galactic is not recommended. ros2 humble and AWSIM v1.1.0 is recommended.
