### ISSUE TITLE
License for `nishishinjuku_autoware_map.zip`

### ISSUE THREAD

**Issue by doganulus** [tier4/AWSIM#21]
Could please you clarify the license status of the files in `nishishinjuku_autoware_map.zip`?

They are not a part of the repository but distributed under Releases as far as I can see.

**Comment by mackierx111** [comment]
@doganulus 
Thanks for pointing that out.
**nishishinjuku_autoware_map.zip is licensed under CC BY-NC.**

I have clearly stated the license of the files to be distributed from the release.
https://tier4.github.io/AWSIM/DeveloperGuide/License/

**Comment by doganulus** [comment]
Thank you @mackierx111. 

It would be good to add LICENSE information in the zip file as well.

**Comment by mackierx111** [comment]
ok. include from next release version.
