### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by H-Kasuyasu** [tier4/AWSIM#244]
Asset/AWSIM/Scripts/Sensors/GnssNavSat/GnssNavSat.cs(98,44):error CS1061:'Transform' does not contain a definition for 'GetPositionAndRotation' and no ...

Kazu

**Comment by khrmt** [comment]
I had the same problem as you.
Although it is not a fundamental solution, I was able to successfully run AWSIM by removing the folder containing "GnssNavSat.cs".

**Comment by H-Kasuyasu** [comment]
Hi, Mr.khrmt

Thank you. I'll try it.

Anyway, why would the TireIV guys upload sources that have never been built?

Kazu

**Comment by mackierx111** [comment]
I decided to delete the script for now. sorry.
