### ISSUE TITLE
Request for improvement of CPU load increase due to deadlock resolution

### ISSUE THREAD

**Issue by HayatoF-68** [tier4/AWSIM#330]
I would like to ask for improvement of the CPU load when applying pull requests [“feat(RandomTraffic): improve yielding rules to avoid deadlocks #243”](https://github.com/tier4/AWSIM/pull/243).

I performed Random simulations immediately after installation of “v.1.2.1 with deadlock removal applied” and “v.1.2.0 before the application was applied”.
Max Vehicle Count was set to 200.

I performed the experiment on the following devices:
・OS: Ubuntu 22.04.3 LTS
・Processor: 13th Gen Intel® Core™ i9-13900K × 32
・Memory: 128GB
・Hardware: Dell Inc. Precision 3660
・Graphic: NVIDIA Corporation GA102GL [RTX A6000] / NVIDIA RTX A6000/PCIe/SSE2A6000

Results:
In v.1.2.1, a significant increase in processing volume was observed after a certain amount of time had passed. The fps also dropped from around 100 at first to single digits.
It was found that the majority of the causes were due to processing related to the newly added "Cognition.CheckRightOfWay"(which is not dominant in v.1.2.0).

Could you please fix it so that the CPU load is reduced even when the Max Vehicle Count is high?

![Screenshot from 2024-07-03 16-33-19](https://github.com/tier4/AWSIM/assets/114726636/1a8ec260-c642-4167-a934-17f47f782e67)
Profiler v.1.2.1

![Screenshot from 2024-07-03 16-34-09](https://github.com/tier4/AWSIM/assets/114726636/d0952c1e-92cc-4cdd-8d82-b7f2db683de0)
Task details v.1.2.1

![1 2 0](https://github.com/tier4/AWSIM/assets/114726636/cfa68271-08ab-415d-b30c-d39c280b64ed)
Profiler v.1.2.0

![v 1 2 0](https://github.com/tier4/AWSIM/assets/114726636/bb982603-3eb0-489f-b257-25b657405838)
Task details v.1.2.0

**Comment by lchojnack** [comment]
Hi @HayatoF-68 

I believe that the issue has been resolved in the PR https://github.com/tier4/AWSIM/pull/337

**Comment by HayatoF-68** [comment]
Thank you for resolving this issue.
It worked fine!
