### ISSUE TITLE
An error occurs when the./setup-dev-env.sh command is executed

### ISSUE THREAD

**Issue by yumianhuli2** [tier4/AWSIM#55]
./setup-dev-env.sh
Setting up the build environment can take up to 1 hour.
>  Are you sure you want to run setup? [y/N] y
/home/kakuhin/.local/bin is already in PATH.

⚠️  All pipx binary directories have been added to PATH. If you are sure you
want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/kakuhin/.local/pipx/logs/cmd_2022-12-31_21.30.25_1_pip_errors.log

pip seemed to fail to build package:
    ansible==6.*

Some possibly relevant errors from pip install:
    pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

Error installing ansible from spec 'ansible==6.*'.

**Comment by shmpwk** [comment]
- Could you share your environment such as Ubuntu version, ROS version?
- Could you share your more error log?  Also I want to check cmd_2022-12-31_21.30.25_1_pip_errors.log
- Maybe your pip environment conflicts with Autoware. I recomend to remove or seperate the environment.
