### ISSUE TITLE
Co-simulation with Autoware-docker container

### ISSUE THREAD

**Issue by joseph16388** [tier4/AWSIM#56]
HI！
Errors are often reported in the process of installing autoware according to the document. Could you plz produce a document of co-simulation of AWSIM and Autoware-Docker version?

**Comment by shmpwk** [comment]
HI! 
The installing process between AWSIM and Autoware docker is not related.
Where do you find the error?  Do you have a docker installation error?

**Comment by shmpwk** [comment]
@joseph16388 
Could you try this?
https://github.com/tier4/AWSIM/issues/81
