### ISSUE TITLE
Assets/Ros2ForUnity/Plugins/Windows seems to be missing (v1.1.0 and main)

### ISSUE THREAD

**Issue by genarks** [tier4/AWSIM#71]
Assets/Ros2ForUnity/Plugins/Windows seems to be missing.

When the simulator is running on Windows, the following log will appear in the Unity Console.
<img width="1136" alt="AWSIMエラー" src="https://user-images.githubusercontent.com/39645272/213396077-a7010482-6748-42b4-9244-b713b412ea4a.png">

(I am new to Autoware. Sorry if I am misguided.)

**Comment by shmpwk** [comment]
@genarks 
Unfortunately, the latest v1.1.0 does not support windows now as described at https://github.com/tier4/AWSIM/releases/tag/v1.1.0 .

Please use v1.0.2 https://github.com/tier4/AWSIM/tree/v1.0.2 for now.

**Comment by genarks** [comment]
Sorry, I did not read that description in v1.1.0.

I will try to use v1.0.2.

Thank you very much.
