### ISSUE TITLE
Please confirm the ubuntu version for quick demo (pose estimation problem)

### ISSUE THREAD

**Issue by Garithe** [tier4/AWSIM#77]
First, while the galactic version is required, it can not be installed on the ubuntu22. But the quick demo page specifies
Ubutnu 22.04
Which OS exactly works? 
Plus, I tried ubuntu 20 + autoware(galactic) + awsim, but autoware doesn't run self pose estimation (quick demo, 5-2).  
I followed:
https://github.com/tier4/AWSIM/blob/v1.0.2/docs/GettingStarted/QuickStartDemo/index.md

**Comment by shmpwk** [comment]
@Garithe 
Thank you for pointing that out.
I had described the docs incorrectly.
I fixed the docs [here](https://github.com/tier4/AWSIM/pull/78).

So the correct combination is
v1.1.0 ~ latest main branch:  Ubuntu22 + humble
~ v1.0.2: Ubuntu20 + galactic

**Comment by shmpwk** [comment]
> Plus, I tried ubuntu 20 + autoware(galactic) + awsim, but autoware doesn't run self pose estimation (quick demo, 5-2). I followed: https://github.com/tier4/AWSIM/blob/v1.0.2/docs/GettingStarted/QuickStartDemo/index.md

Your environment and procedures seem to correct.
Do you have some error when `./setup-dev-env.sh` or `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-w"` ?

**Comment by Garithe** [comment]
@shmpwk 
I think I waited for a while..
How to know if it launches well?
I think I waited until the image is similar to that in instruction.

**Comment by shmpwk** [comment]
> How to know if it launches well?

I recommend to grep error
```
ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit map_path:=<your mapfile location> | grep error
```
```
ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit map_path:=<your mapfile location> | grep die
```
If you get some outputs when executing the above command, could you share them?

**Comment by shmpwk** [comment]
Could you share your picture of RViz to judge the whether it is ok?

**Comment by Garithe** [comment]
@shmpwk Sorry I have reinstalled OS for some reason. 
But I remember that the AutowareStatePanel show INT for all items. 
And I tried to add start pose and goal by somewhat 2d pose goal or something, the car is now shown on map as expected.

**Comment by shmpwk** [comment]
>  the car is now shown on map as expected
You mean your problem has been solved? 
If so, could you close this issue?

**Comment by shmpwk** [comment]
> The previous reply was wrong. I meant the car was NOT shown on map.

Ok, then could you share https://github.com/tier4/AWSIM/issues/77#issuecomment-1403860336 or https://github.com/tier4/AWSIM/issues/77#issuecomment-1403863634 after your reinstallation is completed.
With the current information, I have no idea what could be causing this.

**Comment by shmpwk** [comment]
@Garithe How is it going?

**Comment by shmpwk** [comment]
@Garithe Please open this issue again if you still have this trouble.
