### ISSUE TITLE
Start the Vehicle

### ISSUE THREAD

**Issue by joseph16388** [tier4/AWSIM#80]
Now I could start unity and simulator smoothly. When I selected 2d global pose according to the tutorial, routing trajectories did occur, but it could not automatically start. What is the reason for this?thank U!

the screen shot is below:
![Screenshot from 2023-01-29 09-43-13](https://user-images.githubusercontent.com/117060507/215300529-beb79761-3563-469f-863d-3213742f82a8.png)

**Comment by shmpwk** [comment]
@joseph16388 
You have to command to start the vehicle by ros2 service as the tutorial says.

**Comment by joseph16388** [comment]
> @joseph16388 You have to command to start the vehicle by ros2 service as the tutorial says.

Yes,after I engae,vehicle could run,thanks!
